CREATE DATABASE M_Opflix

USE M_Opflix

CREATE TABLE Usuarios(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(200) NOT NULL,
	Email VARCHAR(200) NOT NULL UNIQUE,
	Senha VARCHAR(200) NOT NULL,
	TipoUsuario VARCHAR(200) NOT NULL
)

CREATE TABLE Categorias(
	IdCategoria INT PRIMARY KEY IDENTITY,
	NomeCategoria VARCHAR(200) NOT NULL UNIQUE
)

CREATE TABLE Tipos(
	IdTipo INT PRIMARY KEY IDENTITY,
	TipoNome VARCHAR(200) NOT NULL UNIQUE
)

CREATE TABLE Veiculos(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	NomeVeiculo VARCHAR(200) NOT NULL UNIQUE
)

CREATE TABLE Classificacoes(
	IdClassificacao INT PRIMARY KEY IDENTITY,
	NomeClassificacao VARCHAR(200) NOT NULL UNIQUE
)

CREATE TABLE Midias(
	IdMidia INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(200) NOT NULL,
	Sinopse TEXT NOT NULL,
	TempoDuracao INT NOT NULL,
	DataLancamento DATE NOT NULL,
	IdClassificacao INT FOREIGN KEY REFERENCES Classificacoes(IdClassificacao) NOT NULL,
	IdCategoria INT FOREIGN KEY REFERENCES Categorias(IdCategoria) NOT NULL,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculos(IdVeiculo) NOT NULL,
	IdTipo INT FOREIGN KEY REFERENCES Tipos(IdTipo) NOT NULL
)

CREATE TABLE Favoritos(
	IdUsuario INT FOREIGN KEY REFERENCES Usuarios(IdUsuario) NOT NULL,
	IdMidia INT FOREIGN KEY REFERENCES Midias(IdMidia) NOT NULL,
)